[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor = "F1ipperKF9EfD821ZbbYjS319LXYiBmjhzkkf5a26rC"

[registry]
# url = "https://api.apr.dev"
url = "https://solana-devnet.g.alchemy.com/v2/IlbN1019P3ZyeBO0RYoRVdTN__tH223L"

[provider]
cluster = "Localnet"
wallet = "/home/matheo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
